### PR TITLE
[RFC] Rename RTFM

### PR DESCRIPTION
**Pull request by jamesmunns**
Link to [Rendered RFC](https://github.com/jamesmunns/rfcs-1/blob/master/text/0000-rename-rtfm.md)

### CODE REVIEW

**Comment by korken89** [comment]
Related old discussion: https://github.com/rtfm-rs/rfcs/issues/11

**Comment by korken89** [comment]
Old name proposals:

- LOVE (Low OVerhead Embedded)
- mrt (Metal Real Time)
- bauble, sunjammer, juggler, implant, unos
- fearless
- kirquk, irqutsk, birqenhead, jirqov, kirqland, sirqap

**Comment by jamesmunns** [comment]
Not to pick on any one name, but I would suggest avoiding `jirqov` as well, as it is somewhat equally offensive when read out loud in english :smile:

**Comment by korken89** [comment]
Noted :)

Another proposal, the one I used for the C++ version: 
- CRECT [Compile-time Reactive Scheduler] (pronounced correct)

**Comment by dbrgn** [comment]
CRECT also sounds a bit... rectal or erect, in case you want to avoid potential negative associations. (If potential negative associations weren't an issue, we probably wouldn't need a rename). It also reminds me of [gamer speech](https://www.urbandictionary.com/define.php?term=rekd) a bit ("U JUST GOT REKD, N00B!!!").

I'm still a fan of my proposed `fearless`, since RTFM enables fearless real-time concurrency on MCUs:

* It matches both the current tagline ("A concurrency framework for building real time systems") as well as the "for the masses" part (because anyone can fearlessly build concurrent systems, without having in-depth knowledge of the dark arts of interrupt handlers and avoiding race conditions). We could also use phrases like "fearless performance", since sometimes the most performant solutions (e.g. mutable statics) are avoided out of fear of data races.
* The tagline could be changed to "A concurrency framework for fearlessly building real time systems"
* The name is still free on crates.io, the only partial conflict would be `fearless_simd`, but I don't think that would be an issue.

While I kind of like the name CompOS (and wouldn't oppose it), calling RTFM an operating system might invoke the wrong associations ("I don't need an OS, I just need a few interrupt handlers, so CompOS is surely not for me!"). The "compile time" part might make the intent more clear, but I could imagine a lot of people will stop reading at "OS".

**Comment by spicyjack** [comment]
Riffing on "juggler" above,  **fiddler**, which is currently free on crates.io, as you're "fiddling" with microcontroller bits

If `irqutsk` (above) were chosen, the mascot for Irkutsk city/oblast, a "babr" (an archaic name for the Siberian Tiger) could be swiped and used as a project logo.  Fun fact, "babr" faces right on the coat of arms for Irkutsk city, and faces left for the coat of arms for Irkutsk oblast.

**Comment by dbrgn** [comment]
As an observation: Reading through #11, I think most people that didn't support the name change said "it's fine and we don't need a rename for political correctness". Actually, in summary there was just 1 person in that whole thread strongly opposing a name change, with the following reasoning:

> the whole "problem" to start with is just a bunch of sissies feeling insecure about an acronym, which obviously can mean different things

The rest of the comments were mostly indifferent or supportive.

For me, I don't have a strong opinion on the rename, but I think the experiences by @jamesmunns in a commercial environment might be a good reason to rethink the current project name. Thus, I'd vote in favor of this RFC. Not because of political correctness, but because just mentioning the name of the cool real-time framework to the management might raise eyebrows. It would be a pity if adoption of RTFM would be hurt by its name.

Case in point:

2020-05-05-174251_638x387_scrot

The last rename request (#11) was not rejected, only put on hold. I think it would be good to make a final decision now, a rename only gets harder the longer the project exists.

**Comment by korken89** [comment]
Hi all, we will discuss this at today's meeting @ 21 CET (50 min from now).

**Comment by perlindgren** [comment]
We have been discussing a bit around the name.
One suggestion could be

RTIC (Real-Time on Integrated Circuits).
Pros:
1 - Easy to pronounce/spell
2 - Not overloaded, should be easy to google
3 - Spoken sounds like arctic (almost), we could use that to associate to its arctic region origin 

Cons:
The irony is lost, Read The Friendly Manual.

**Comment by perlindgren** [comment]
RTIC 

Real-Time Interrupt-driven Concurrency

**Comment by korken89** [comment]
During today's meeting we have descided to pursue RTIC as the new name for this framework.
There will now be a 1 week FCP on this RFC which ends on the **17th of May, 22:00 CET**.

Thanks all for helping and coming with feedback here!

**Comment by TeXitoi** [comment]
OK for me for RTIC

**Comment by dbrgn** [comment]
I guess this has now been completed? :slightly_smiling_face:

**Comment by korken89** [comment]
bors merge

**Pull request merged**
